In [4]:
import numpy as np
import pandas as pd

In [5]:
data = {
    'text': [
        "I love this product!",
        "The service was terrible.",
        "The movie was amazing.",
        "I feel neutral about it.",
        "The experience was disappointing.",
        "This is the best thing ever!",
        "I can't stand this.",
    ],
    'output': [
        1,
        0,
        1,
        0,
        0,
        1,
        0
    ]
}
df = pd.DataFrame(data)
print(df)


                                text  output
0               I love this product!       1
1          The service was terrible.       0
2             The movie was amazing.       1
3           I feel neutral about it.       0
4  The experience was disappointing.       0
5       This is the best thing ever!       1
6                I can't stand this.       0


In [6]:
df.head()

text  output
0               I love this product!       1
1          The service was terrible.       0
2             The movie was amazing.       1
3           I feel neutral about it.       0
4  The experience was disappointing.       0

# Uni-grams

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1, 1))
vectorizer_lowercase = CountVectorizer(lowercase=True, stop_words='english')
bow = cv.fit_transform(df['text'])


In [19]:
print(cv.vocabulary_)

{'love': 10, 'this': 19, 'product': 13, 'the': 17, 'service': 14, 'was': 20, 'terrible': 16, 'movie': 11, 'amazing': 1, 'feel': 7, 'neutral': 12, 'about': 0, 'it': 9, 'experience': 6, 'disappointing': 4, 'is': 8, 'best': 2, 'thing': 18, 'ever': 5, 'can': 3, 'stand': 15}


# Vocabulary Count

In [23]:
import collections

all_text = ' '.join(df['text'])
words = all_text.split()
vocabulary = collections.Counter(words)

unique_vocab_count = len(vocabulary.keys())
print("Count of Unique Vocabulary:", unique_vocab_count)


Count of Unique Vocabulary: 25


In [24]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())
print(bow[4].toarray())

[[0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1]]
[[0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1]]
[[1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0]]
[[0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1]]


# Testing on untrained Document

In [25]:
cv.transform(["the experience was bit disappointing"]).toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]])

# Bi-grams

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv_2 = CountVectorizer(ngram_range=(2, 2))
vectorizer_lowercase = CountVectorizer(lowercase=True, stop_words='english')


In [27]:
bow=cv_2.fit_transform(df['text'])

In [28]:
print(cv_2.vocabulary_)

{'love this': 6, 'this product': 17, 'the service': 14, 'service was': 9, 'was terrible': 20, 'the movie': 13, 'movie was': 7, 'was amazing': 18, 'feel neutral': 4, 'neutral about': 8, 'about it': 0, 'the experience': 12, 'experience was': 3, 'was disappointing': 19, 'this is': 16, 'is the': 5, 'the best': 11, 'best thing': 1, 'thing ever': 15, 'can stand': 2, 'stand this': 10}


# Tri-Gram

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv_3 = CountVectorizer(ngram_range=(3, 3))
vectorizer_lowercase = CountVectorizer(lowercase=True, stop_words='english')


In [30]:
bow=cv_3.fit_transform(df['text'])

In [31]:
print(cv_3.vocabulary_)

{'love this product': 5, 'the service was': 12, 'service was terrible': 8, 'the movie was': 11, 'movie was amazing': 6, 'feel neutral about': 3, 'neutral about it': 7, 'the experience was': 10, 'experience was disappointing': 2, 'this is the': 13, 'is the best': 4, 'the best thing': 9, 'best thing ever': 0, 'can stand this': 1}


# Tetra-gram

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv_4 = CountVectorizer(ngram_range=(4, 4))
vectorizer_lowercase = CountVectorizer(lowercase=True, stop_words='english')


In [33]:
bow=cv_4.fit_transform(df['text'])

In [34]:
print(cv_4.vocabulary_)

{'the service was terrible': 5, 'the movie was amazing': 4, 'feel neutral about it': 0, 'the experience was disappointing': 3, 'this is the best': 6, 'is the best thing': 1, 'the best thing ever': 2}


# Penta-gram

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
cv_5 = CountVectorizer(ngram_range=(5, 5))
vectorizer_lowercase = CountVectorizer(lowercase=True, stop_words='english')


In [42]:
bow=cv_5.fit_transform(df['text'])

In [43]:
print(cv_5.vocabulary_)

{'this is the best thing': 1, 'is the best thing ever': 0}


# Exceeding range from Vocabulary size

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
cv_6 = CountVectorizer(ngram_range=(7, 7))
vectorizer_lowercase = CountVectorizer(lowercase=True, stop_words='english')


In [51]:
bow=cv_6.fit_transform(df['text'])

ValueError: empty vocabulary; perhaps the documents only contain stop words

# Bi-gram and Tetra-gram

In [52]:
from sklearn.feature_extraction.text import CountVectorizer
cv_7 = CountVectorizer(ngram_range=(2, 4))
vectorizer_lowercase = CountVectorizer(lowercase=True, stop_words='english')


In [53]:
bow=cv_7.fit_transform(df['text'])

In [54]:
print(cv_7.vocabulary_)

{'love this': 13, 'this product': 38, 'love this product': 14, 'the service': 31, 'service was': 19, 'was terrible': 41, 'the service was': 32, 'service was terrible': 20, 'the service was terrible': 33, 'the movie': 28, 'movie was': 15, 'was amazing': 39, 'the movie was': 29, 'movie was amazing': 16, 'the movie was amazing': 30, 'feel neutral': 7, 'neutral about': 17, 'about it': 0, 'feel neutral about': 8, 'neutral about it': 18, 'feel neutral about it': 9, 'the experience': 25, 'experience was': 5, 'was disappointing': 40, 'the experience was': 26, 'experience was disappointing': 6, 'the experience was disappointing': 27, 'this is': 35, 'is the': 10, 'the best': 22, 'best thing': 1, 'thing ever': 34, 'this is the': 36, 'is the best': 11, 'the best thing': 23, 'best thing ever': 2, 'this is the best': 37, 'is the best thing': 12, 'the best thing ever': 24, 'can stand': 3, 'stand this': 21, 'can stand this': 4}
