In [1]:
import numpy as np
import pandas as pd

In [24]:
data = {
    'text': [
        "I love this product!",
        "The service was terrible.",
        "The movie was amazing.",
        "I feel neutral about it.",
        "The experience was disappointing.",
        "This is the best thing ever!",
        "I can't stand this.",
    ],
    'output': [
        1,
        0,
        1,
        0,
        0,
        1,
        0
    ]
}
df = pd.DataFrame(data)
print(df)


                                text  output
0               I love this product!       1
1          The service was terrible.       0
2             The movie was amazing.       1
3           I feel neutral about it.       0
4  The experience was disappointing.       0
5       This is the best thing ever!       1
6                I can't stand this.       0


In [3]:
df.head()

text    output
0               I love this product!  Positive
1          The service was terrible.  Negative
2             The movie was amazing.  Positive
3           I feel neutral about it.   Neutral
4  The experience was disappointing.  Negative

# Using Machine Learning Approach

In [18]:
bow=cv.fit_transform(df['text'])

In [19]:
print(cv.vocabulary_)

{'love': 10, 'this': 19, 'product': 13, 'the': 17, 'service': 14, 'was': 20, 'terrible': 16, 'movie': 11, 'amazing': 1, 'feel': 7, 'neutral': 12, 'about': 0, 'it': 9, 'experience': 6, 'disappointing': 4, 'is': 8, 'best': 2, 'thing': 18, 'ever': 5, 'can': 3, 'stand': 15}


# Vocabulary Count

In [20]:
all_text = ' '.join(df['text'])
words = all_text.split()
vocabulary = Counter(words)

unique_vocab_count = len(vocabulary.keys())
print("Count of Unique Vocabulary:", unique_vocab_count)

Count of Unique Vocabulary: 25


In [21]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())
print(bow[4].toarray())

[[0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1]]
[[0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1]]
[[1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0]]
[[0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1]]


# Testing on untrained Document

In [13]:
cv.transform(["the experience was bit disappointing"]).toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]])